### ISSUE TITLE
As a developer, I want the Search UI to use the PDS API and Registry for searching metadata

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/pds.nasa.gov-search-prototype#31]
## Motivation
...so that the search UI is decoupled from the ElasticSearch backend and eventually benefit for API extensions (e.g. the one which would use the graph database in addition to elasticsearch index)

## Additional Details

The API documentation is available on https://nasa-pds.github.io/pds-api/

Demo deployment to be used for development is available on https://pds-gamma.jpl.nasa.gov/api/swagger-ui.html

## Acceptance Criteria
We want the following from this task:
- [ ] upgrade the search UI to use the PDS API

**Comment by tloubrieu-jpl** [comment]
@tloubrieu-jpl  We need an interim conclusion on that...

**Comment by jordanpadams** [comment]
Email traffic between @eddiesarevalo and @tloubrieu-jpl regarding issues with the search API for completing this implementation for the time being.

[search_api_upgrades_for_search_ui.pdf](https://github.com/NASA-PDS/PDS.nasa.gov-Search/files/6750814/search_api_upgrades_for_search_ui.pdf)

**Comment by jordanpadams** [comment]
moved the initial investigation to new ticket #33 . this requirement will live on until we can complete the implementation

**Comment by jordanpadams** [comment]
closing this as wont fix. all new search dev has moved to https://github.com/NASA-PDS/wds-react/
