### ISSUE TITLE
As a user, I want the UI to use the WDS Horizon

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/pds.nasa.gov-search-prototype#32]
## Motivation
...so that it looks good and consistent with other nasa web UIs.

## Acceptance Criteria
**Given** 
**When I perform** 
**Then I expect**

**Comment by jordanpadams** [comment]
closing this as wont fix. all new search dev has moved to https://github.com/NASA-PDS/wds-react/
